name: Continuous Integration and Delivery

on:
  push:
    branches:
      - master
      - docker-build

env:
  WEB_IMAGE: ghcr.io/abutalhadanish/blog-with-cicd/web:deploy

jobs:

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Set environment variables
        run: |
          echo "WEB_IMAGE=$(echo ${{env.WEB_IMAGE}} )" >> $GITHUB_ENV
          # echo "NGINX_IMAGE=$(echo ${{env.NGINX_IMAGE}} )" >> $GITHUB_ENV
      - name: Log in to GitHub Packages
        run: echo ${PERSONAL_ACCESS_TOKEN} | docker login ghcr.io -u ${{ secrets.NAMESPACE }} --password-stdin
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Pull images
        run: |
          docker pull ${{ env.WEB_IMAGE }} || true
          # docker pull ${{ env.NGINX_IMAGE }} || true
      - name: Build images
        run: |
          docker build -f Dockerfile -t ${{ env.WEB_IMAGE }} .
          # docker-compose -f docker-compose.yml build
      - name: Push images
        run: |
          docker push ${{ env.WEB_IMAGE }}
          # docker push ${{ env.NGINX_IMAGE }}
